name: coverage

on:
  push:
    paths:
      - "**.php"
      - ".github/workflows/coverage.yml"
      - "phpunit.xml.dist"
      - "composer.json"
      - "composer.lock"

jobs:
  pest:
    name: pest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, xdebug
          coverage: xdebug

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Pest coverage
        run: ./vendor/bin/pest --coverage --min=50
